modLoader="javafml"
loaderVersion="[41,)"
license="MIT"
issueTrackerURL="https://discord.gg/A8YKbxv25w"

[[mods]]
modId="simplesponge"
version="1.0.2"
displayName="Simple Sponge"
displayURL="https://github.com/JackyyTV/SimpleSponge"
logoFile="logo.png"
credits="Jackyy, ThatGamerBlue"
authors="MaxIsH0t"
description='''
OpenBlocks Sponge port for 1.18.2+, with some extra sprinkles!
'''

[[dependencies.simplesponge]]
modId="forge"
mandatory=true
versionRange="[41,)"
ordering="NONE"
side="BOTH"
[[dependencies.simplesponge]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"